import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import NavbarComponent from "./components/Header/NavbarComponent";
import FooterComponent from "./components/Footer/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CSTAD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="https://istad.co/resources/img/logo_md.png"/>
      </Head>
      <body className={inter.className}>
        <NavbarComponent/>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
